config/routes.rb
AGRIZONDE::Application.routes.draw do
  resources :events

  get "data_reference/index"
  get "data_reference/show_data"
  resources :temperature_humidities

  # welcomeページ
  root :controller => 'temperature_humidities', :action => 'index'

end

app/models/temperature_humidity.rb
# coding: utf-8
class TemperatureHumidity < ActiveRecord::Base
  require 'csv'
  require 'kconv'

  # WATCH_LOGGERのlogのcsvファイルをテーブルに挿入または更新する
  def self.import_watch_logger_log_csv(watch_logger_log_csv)
    if !watch_logger_log_csv
      return FAILURE_CREATE_OR_UPDATE
    end

    # csvファイルをデータベースに挿入
    return create_or_update_watch_logger_log_csv(watch_logger_log_csv)
  end

  # 指定された日付の温度湿度を時間の昇順に取得する
  def self.get_TemperaturHumidites_where_log_date_order_by_log_time(log_date)
    TemperatureHumidity.where('log_date = ?', log_date).order('log_time ASC')
  end

  # 全日付の平均温度、平均湿度を取得する
  def self.get_all_date_avg_temp_and_hum()
    TemperatureHumidity.find_by_sql('SELECT log_date, AVG(temperature) AS "avg_temp", AVG(humidity) AS "avg_hum" FROM temperature_humidities GROUP BY log_date')
  end

  private
  # WATCH_LOGGERのlogのcsvファイルから日付、時間、場所、温度、湿度を挿入または更新する。挿入された場合
  def self.create_or_update_watch_logger_log_csv(watch_logger_log_csv)
    result_string = ''
    # ファイルを読み込む
    watch_logger_log_csv_data = watch_logger_log_csv.read

    # CSVファイルを走査する
    ActiveRecord::Base.transaction do
      place_id = 0
      CSV.parse(watch_logger_log_csv_data.kconv(Kconv::UTF8, Kconv::SJIS)) do |row|
        if 'H2' == row[0]
          # TODO 場所を画面から選択できるようにする、またはWATCH_LOGGERのlogのcsvから場所IDを取得する
          # place_idをセット
          place_id = 1
        elsif 'SD' == row[0]
          exist_hash = {
              log_date: row[1].split[0],
              log_time: row[1].split[1],
              place_id: place_id
          }
          if TemperatureHumidity.exists?(exist_hash)
            logger.info "データが既に存在しています：#{exist_hash}"
            temperature_humidity_data = TemperatureHumidity.find_by(exist_hash)
            temperature_humidity_data.update_attributes(temperature: row[2], humidity: row[3])
            result_string = SUCCESS_UPDATE
          else
            # 日付、場所、温度、湿度を挿入する
            create_hash = {
                log_date: row[1].split[0],
                log_time: row[1].split[1],
                temperature: row[2],
                humidity: row[3],
                place_id: place_id
            }
            TemperatureHumidity.create(create_hash)
          end
        end
      end
    end
    watch_logger_log_csv.rewind

    if SUCCESS_UPDATE != result_string
      result_string = SUCCESS_CREATE
    end

    return result_string
  end
end

app/controllers/temperature_humidities_controller.rb
# coding: utf-8
class TemperatureHumiditiesController < ApplicationController
  layout 'common_layout'
  before_action :set_temperature_humidity, only: [:show, :edit, :update, :destroy]

  # GET /temperature_humidities
  # GET /temperature_humidities.json
  def index
    #@temperature_humidities = TemperatureHumidity.all
    #@temperature_humidity = TemperatureHumidity.new
  end

  # GET /temperature_humidities/1
  # GET /temperature_humidities/1.json
  def show
  end

  # GET /temperature_humidities/new
  def new
    @temperature_humidity = TemperatureHumidity.new
  end

  # GET /temperature_humidities/1/edit
  def edit
  end

  # 画面から入力された温湿度ロガーデータCSVファイルを、データベースに挿入または更新する
  def create
    if !params[:temp_hum_file_path]
      # ファイルパスが入力されていない場合
      result_string = REQUIRE_ERROR
    else
      # WATCH_LOGGERのログファイルをインポート
      result_string = TemperatureHumidity.import_watch_logger_log_csv(params[:temp_hum_file_path])
      # 平均温度と湿度を全て走査してeventsテーブルに詰めなおす
      Event.reflesh_create_avg_temp_and_hum
    end

    # メッセージをセット
    message_string = ''
    if REQUIRE_ERROR == result_string
      # 必須チェックエラーメッセージ
      message_string = message_string + t('temperature_humidities.index.watch_logger_log_error_message')
    end

    if SUCCESS_CREATE == result_string
      # 登録メッセージ
      message_string = message_string + t('temperature_humidities.index.watch_logger_log_create_message')
    elsif SUCCESS_UPDATE == result_string
      # 更新メッセージ
      message_string = message_string + t('temperature_humidities.index.watch_logger_log_update_message')
    end

    flash[:notice] = message_string
    redirect_to and return
  end

# PATCH/PUT /temperature_humidities/1
# PATCH/PUT /temperature_humidities/1.json
  def update
    respond_to do |format|
      if @temperature_humidity.update(temperature_humidity_params)
        format.html { redirect_to @temperature_humidity, notice: 'Temperature humidity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @temperature_humidity.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /temperature_humidities/1
# DELETE /temperature_humidities/1.json
  def destroy
    @temperature_humidity.destroy
    respond_to do |format|
      format.html { redirect_to temperature_humidities_url }
      format.json { head :no_content }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_temperature_humidity
    @temperature_humidity = TemperatureHumidity.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def temperature_humidity_params
    params.require(:temperature_humidity).permit(:date, :time, :temperature, :humidity)
  end

end

app/helpers/temperature_humidities_helper.rb
module TemperatureHumiditiesHelper
end

app/views/temperature_humidities/_form.html.erb
<%= form_for(@temperature_humidity) do |f| %>
  <% if @temperature_humidity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temperature_humidity.errors.count, "error") %> prohibited this temperature_humidity from being saved:</h2>

      <ul>
      <% @temperature_humidity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_area :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_area :time %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.number_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :humidity %><br>
    <%= f.number_field :humidity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temperature_humidities/_logger_data_input_form.html.erb
<%= form_tag '/temperature_humidities', {method: 'post',multipart: true} do %>
    <div class="field">
      <label>WATCH LOGGER のログファイルパス入力</label><br>
      <%= file_field_tag 'temp_hum_file_path', :class => 'file_filed' %>
    </div>
    <div class="actions">
      <%= submit_tag '登録' ,{class:'submit_button'} %>
    </div>
<% end %>

app/views/temperature_humidities/edit.html.erb
<h1>Editing temperature_humidity</h1>

<%= render 'form' %>

<%= link_to 'Show', @temperature_humidity %> |
<%= link_to 'Back', temperature_humidities_path %>

app/views/temperature_humidities/index.html.erb
<h1>ロガーデータ登録</h1>

<table>

  <%= render 'logger_data_input_form' %>

</table>

app/views/temperature_humidities/new.html.erb
<h1>New temperature_humidity</h1>

<%= render 'form' %>

<%= link_to 'Back', temperature_humidities_path %>

app/views/temperature_humidities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @temperature_humidity.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @temperature_humidity.time %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @temperature_humidity.temperature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @temperature_humidity.humidity %>
</p>

<%= link_to 'Edit', edit_temperature_humidity_path(@temperature_humidity) %> |
<%= link_to 'Back', temperature_humidities_path %>